name: Cypress E2E Tests

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
        # Checkout the branch
      - name: Checkout
        uses: actions/checkout@v3
        
        # Create the test environment file from Actions Secrets
      - name: Echo secrets
        run: |
          echo $TEST_ENV_FILE >> src/environments/environment.test.ts
          cat src/environments/environment.test.ts
        shell: bash
        env:
          TEST_ENV_FILE : ${{secrets.ENVIRONMENT_TEST_TS}}
          
        # Setup pnpm package manager, as we don't use npm for our project
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
          
        # Get the path that pnpm uses to store files, so we can retrieve that from the build cache
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
          
        # Retrieve the pnpm build cache
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
        # Install dependencies, won't really do much since we have the cache
      - name: Install dependencies
        run: pnpm install
        
        # Install Cypress, won't really do much since we have the cache
      - name: Install Cypress
        run: pnpm install -g cypress@12.8.1 && cypress install
        
        # FINALLY run our tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.6.1
        with:
          build: pnpm run build --configuration test
          start: pnpm run ng serve --configuration test
          install: false
          
        # Upload screenshots of failed test and all test videos to the build artifacts
      - name: Upload failed screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
         
      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
