name: Cypress E2E Tests

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Echo secrets
        run: |
          echo $TEST_ENV_FILE >> src/environments/environment.test.ts
          cat src/environments/environment.test.ts
        shell: bash
        env:
          TEST_ENV_FILE : ${{secrets.ENVIRONMENT_TEST_TS}}
          
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
          
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
          
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - uses: actions/cache@v3
        name: Setup Cypress cache
        with:
          path: '/home/runner/.cache/Cypress'
          key: ${{ runner.os }}-cypress-binary-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-binary-
      
      - name: Install dependencies
        run: pnpm install
        
      - name: Install Cypress
        run: pnpm dlx cypress install
        
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: pnpm run build --configuration test
          start: pnpm run ng serve --configuration test
          install: false
          
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
